version: '2'

services:
    db:
        image: mysql
        volumes:
          - "./.data/db:/var/lib/mysql"
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ml_test
          MYSQL_USER: user
          MYSQL_PASSWORD: userpass
        ports:
          - 3306:3306
    proxy:
        build: ./
        volumes:
          - "./proxy:/src/app"
        ports:
          - "8080:3000"
        depends_on:
          - "db"
        command: ["/src/app/wait_db.sh", "db", "user", "userpass"]
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        environment:
          - transport.host=0.0.0.0
          - xpack.security.enabled=false
    kibana:
        image: docker.elastic.co/kibana/kibana:5.4.0
        environment:
          - transport.host=0.0.0.0
          - xpack.security.enabled=false
        ports:
          - 8081:5601